# Generated by Django 4.2.7 on 2023-11-27 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام لامپ')),
                ('status', models.CharField(choices=[('0', 'OFF'), ('1', 'ON')], default='0', max_length=10, verbose_name='وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام سنسور')),
                ('description', models.CharField(max_length=255, verbose_name='جزئیات سنسور')),
            ],
        ),
        migrations.CreateModel(
            name='SensorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='مقدار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sensor', verbose_name='سنسور')),
            ],
        ),
    ]
