# Generated by Django 4.2.7 on 2023-11-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordetail',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='sensor',
            name='quantity',
            field=models.CharField(default='درجه', max_length=100, verbose_name='واحد'),
        ),
    ]
